### ISSUE TITLE
How to read a kml file?

### ISSUE THREAD

**Issue by makelove** [eisoldt/simplekml#2]
I have some kml files, how to read them ?
how to parse kml file ?

Your document seem don't have open or read file function

solved, use pyKML ,done

**Comment by stodge** [comment]
For anyone else who stumbles across this package and has the same question, the documentation says it only supports creating KML/KMZ. It doesn't support loading existing KML or KMZ files:

`The python package simplekml was created to generate kml (or kmz).`

https://simplekml.readthedocs.io/en/latest/index.html
