### ISSUE TITLE
Using a street address with simplekml instead of coordinates

### ISSUE THREAD

**Issue by 3nterausername** [eisoldt/simplekml#7]
Hello, 

SimpleKML is a great tool - thank you

I'm having trouble using a street address (as opposed to coords) as an input to simpleKML, for use with Google mymaps or Google Earth. 

Does anyone have any tips on how to configure the input to make it functional. Perhaps some sample code if possible.

**Comment by docjason** [comment]
You should be able to create KML like this - having an address but no Point geometry.

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
    <Placemark>
        <name>Google place</name>
        <address>1600 Amphitheatre Parkway, Mountain View, CA</address>
    </Placemark>
</kml>
```

This code in simplekml, however, automatically creates a Point geometry at 0,0 which prevents GE Pro from using the address and jumps to 0,0 on the map.

```
import simplekml

kml = simplekml.Kml()
pnt = kml.newpoint(name="Google place", address="1600 Amphitheatre Parkway, Mountain View, CA")
kml.save("address.kml")
```

Ouput:

```
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2">
    <Document id="1">
        <Placemark id="3">
            <name>Google place</name>
            <address>1600 Amphitheatre Parkway, Mountain View, CA</address>
            **<Point id="2">
                <coordinates>0.0, 0.0, 0.0</coordinates>
            </Point>**
        </Placemark>
    </Document>
</kml>
```

Recommend adding a new function newplacemark() with address=XXX parameter to allow creating a placemark without a geometry.

**Comment by eisoldt** [comment]
Thanx to Jason this issue is fixed
